# Generated by Django 2.1.2 on 2019-08-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190803_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '化石DB', 'verbose_name_plural': '化石DB'},
        ),
    ]
