# Generated by Django 2.1.2 on 2019-08-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190803_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
